const appname = "eMart Seller App",
login = "Login",
welcome = "Hi, Welcome to",
email = "Email",
password = "Password",
forgotPassword = "Forgot Password?",
anyProblem = "In case of any difficulty, contact administration",
emailHint = "eg. vendor@smart.com",
passwordHind = " * * * * * * ",
dashboard = "Dashboard",
orders = "Orders",
products = "Products",
settings = "Settings",
rating = "Rating",
totalSale = "Total Sales",
popular = "Popular Products",
unpaid = "Unpaid",
shopSettings = "Shop Settings",
logout = "Logout",
changeImage = "Change Image",
messages = "Messages",
editProfile = "Edit Profile",
featured = "Featured",
edit = "Edit",
remove = "Remove",
loginTo = "Login to your account",
credit = "@DharmendraDevs";

// shop settings string
const nameHint = "eg. Vendor Name", shopDscHint = "Enter your shop description", shopWebsiteHint = "eg. vendor.emart.com", shopMobileHint = "eg. +91254695874", shopAddressHint = "eg. Shona Road", description = "Description", mobile = "Shop Mobile", website = "Shop Website", name = "Shop Name", address = "Shop Address";
